AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template to Create EC2 Stack using Cross Stack References.In this Example
Subnet ID and Security Group are Imported from Another Stack.'
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
     - t2.micro
     - m1.small
     - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
Resources:
  EC2Instance:
   Type: AWS::EC2::Instance 
   Properties:
    InstanceType: !Ref 'InstanceType'
    KeyName: !Ref 'KeyName'
    ImageId: ami-0912f71e06545ad88
    SecurityGroupIds: 
    - !ImportValue mySecurityGroup
    SubnetId: !ImportValue MyPublicSubnet2
    UserData:
        Fn::Base64: !Sub |
              #!/bin/bash
              yum update -y aws-cfn-bootstrap;
              yum install -y httpd;
              echo "<html>My Name is Narendra Singh and this is my EC2 Instance</html>" > /var/www/html/index.html;
              cd /var/www/html;
              chmod 755 index.html;
              service httpd start;
              chkconfig httpd on;
Outputs:
  InstanceId1:
    Description: InstanceId of the first EC2 instance
    Value: !Ref 'EC2Instance'
  PublicIP1:
    Description: IP of the first EC2 instance
    Value: !GetAtt [EC2Instance, PublicIp]
